### ISSUE TITLE
画像表示されない問題

### ISSUE THREAD

**Issue by yui1308** [yuimelody/web_app#6]
## 画像が表示されません
タイトル通り表示したい画像が  
表示できません。  
どこを改善したらいいですか？  

##### p.s.
templeteにimgというフォルダを追加しました

**Comment by Gorira-Banana** [comment]
修正しておきます。
一番手っ取り早いのはstaticファイルにimgファイルを追加する方法で
img src="{% static 'img/hogehoge.jpg' %}"/
のように書くと反映されると思います。
またpythonでwebからスクレイピングする方法も考えられます。

by Gorira-Banana
